### ISSUE TITLE
Display enough decimals for Magnitudes

### ISSUE THREAD

**Issue by Quezacoatl1** [startailcoon/Gridcoinstats-IssuesTracker#1]
Hey startail :)

Is it possible to display at least 2 decimals on magnitude numbers? We will have the need for more decimals with more users anyway, and that way I could get rid of using the list explainmagnitude which output is not reliable in terms of magnitudes (because its a local lookup I suppose) and format (which is dependent on the NN participation I think).

Kind Regards, Quez

**Comment by startailcoon** [comment]
Agree that the networks magnitude will most likely require more decimals as the network grows. We currently have two places where we display magnitude, and only one place where we display the total magnitude in decimals of 2.

We could make all spaces of CPID Magnitude display the same amount of decimals (depending on space).

## CPID Staking History (https://gridcoinstats.eu/cpid)
![image](https://user-images.githubusercontent.com/12114550/35766227-fe7af002-08d3-11e8-8a74-2c8357d314e1.png)

## CPID Details Page
![image](https://user-images.githubusercontent.com/12114550/35766224-e9b16ac0-08d3-11e8-9c61-0ad61ace5a2f.png)

![image](https://user-images.githubusercontent.com/12114550/35766233-33e71450-08d4-11e8-847e-a2f13d8b2f40.png)

**Comment by startailcoon** [comment]
At present time, I don't think that the client generates blocks with decimal magnitudes. I've changed my database structure to allow a magnitude with 2 decimals up to 99999,99.

For the moment I think this would suffice. The `Estimated Mag` table will not contain any decimals per project, since it's to unsure to be relied upon 100% today. The `Estimated Mag Total` is still 2 decimals, as before though.
