### ISSUE TITLE
News and Updates not updating steem content

### ISSUE THREAD

**Issue by startailcoon** [startailcoon/Gridcoinstats-IssuesTracker#3]
Since a few months now, the news and updates section isn't updated with new data for the Steem sections. 

I'm working on making the section converted to use SteemJS as well as possibilities to add other sources.

- [ ] Fix Steem Source
- [ ] Add various other sources
- [ ] Create sub-menu sections for sources (like Steem, BOINC Projects, Twitter)

**Comment by grcjamezz** [comment]
Finally , I have been msging and trying to contact you ( no contact email address on site ) and you have ignored all of my msgs in private and public , steemit comments etc and it's not updated since 8/2017 and since sponsored by the foundation thought it would be a priority to have a fully working website.. Please add a way to contact that you actually pay attention to like webmin@ or webmaster@ or admin@gridcoinstats.eu as who knows if this will be monitored.. Just feels like you have completely ignored and blown off people like myself whom has only ever tried to help especially with typo's. Does not sit well with me , I do not know how the rest of the community feels but leaves a bad taste in my mouth...

**Comment by startailcoon** [comment]
Fixing the issues with feeds from steem is still one of my priorities. This has never changed.

I've explained to you before why I have no e-mail posted on the page, but I will consider it. It does not mean I have more time responding to questions than I do today.

# The page is not sponsored by the fundation
This is not going to be true however many times you write this. If you spread this around more I will not reply to you again.

**Comment by startailcoon** [comment]
This issue has now been resolved and uses [SteemJS](https://github.com/steemit/steem-js).
