### ISSUE TITLE
Page not rendering projects

### ISSUE THREAD

**Issue by polpas** [startailcoon/Gridcoinstats-IssuesTracker#37]
There is no data in the fields. I receive no transaction since 16 of May. Is it normal?

**Comment by forestacorn** [comment]
I am experiencing the same issue, where the Active Projects section displays **No Active Projects** where a couple of weeks ago the eight projects I am still working on were displayed.

**Comment by startailcoon** [comment]
@polpas, can you please give me a link to your profile so I can look at it? 

@forestacorn this is a problem I got aware of a few days ago. I will look into how big of a problem this is and if it can be fixed. Hopefully I just need to restart some services for this to work again.

**Comment by polpas** [comment]
https://www.gridcoinstats.eu/cpid/7aeb878ec8f98560319a70f5ebeef6d9

Francisco R. Martins

**Comment by startailcoon** [comment]
@polpas did you recieve anything to the listed addresses that isn't showing up? If you've recieved assets to any other address they aren't connected to your CPID profile. This is not a bug, but rather by design on the chain and is nothing that can be done about. Your wallet is always correct.

@forestacorn this should now be solved and updates will come in momentarily.
